### ISSUE TITLE
Can't parse these time string

### ISSUE THREAD

**Issue by nifflerfox** [bcampbell/fuzzytime#1]
"12/01/2016 - 12:19"
"12/01 - 12:19:01" // only parse 12:19:01
"12-01-2016 - 12:19"
"20-12-2016"
"20/12/2016"
"20.12.2016"
"03:43 21-12-2016"
"12/16/2016 - 08:00am"
"12/21/16 at 1:12 am"

fuzzytime is the best time string parser for now, thank you very much!

**Comment by bcampbell** [comment]
Thanks!

The problem is that these dates are all ambiguous - some countries use DD/MM/YYYY and some use MM/DD/YYYY.
To deal with this you need to use a [`Context`](https://godoc.org/github.com/bcampbell/fuzzytime#Context).
The `Context` lets you make a decision on which format to prefer.

There are a couple of predefined contexts. So, for example, to assume USA MM/DD/YYYY format (and US timezone names), you could do:
```
dt,_,_ := fuzzytime.USContext.Extract("4/3/2016")
```

Hope this helps!
